### ISSUE TITLE
world preloader works but..

### ISSUE THREAD

**Issue by InactiveCoyote** [gompocp/VRChatMods#1]
when it finish downloading the option to go to friend profile or world and it shows nothing

**Comment by gompocp** [comment]
Can you elaborate please? Are you using the latest version (on github, not in the vrcmg) Does the popup show correctly? If not do you have "Show popup on complete" disabled in settings. What happens when you click on "Go to world page"? etc. Are there any errors? Do you have a log file? I can look at?

**Comment by InactiveCoyote** [comment]
here i had to upload it on discord due to the github on 10mb

https://discord.com/channels/@me/771779778272296980/852714973486776320

**Comment by InactiveCoyote** [comment]
here the link for the video i had to use discord

https://cdn.discordapp.com/attachments/771779778272296980/852714969980076092/VRChat_2021-06-10_20-00-00.mp4

**Comment by gompocp** [comment]
It appears I don't have access to that video (or it has been deleted)

**Comment by InactiveCoyote** [comment]
ok what about this https://youtu.be/p9C_9ulddrU

**Comment by gompocp** [comment]
I see the problem now. Are you using the oculus store version of vrchat or steam btw?

**Comment by InactiveCoyote** [comment]
steam version.

**Comment by InactiveCoyote** [comment]
now melonloader updated and now it doesn't work.

**Comment by gompocp** [comment]
Should be working for the most part with this version: https://github.com/gompocp/VRChatMods/releases/download/2021-06-22/WorldPredownload.dll. Lemme know if it works for you and I can close this issue

**Comment by InactiveCoyote** [comment]
it works now thx.

**Comment by InactiveCoyote** [comment]
ill close it now
